image: node:8.11.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - git config --global user.email "yongjun.ji@ucarinc.com"
  - git config --global user.name "yongjun"
  - npm install hexo-cli -g
  - npm install
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - gitee
