# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu 导航菜单显示{[@page:名字,@url:地址,@icon:图标]}
menu:
- page: 主页
  url: /
  icon: fa-home
- page: 后端
  url: /categories/后端/
  icon: fa-tag
- page: 工具
  url: /categories/工具/
  icon: fa-tag
- page: 关于
  url: /about/
  icon: fa-book
- page: 时间轴
  url: /archives/
  icon: fa-list

## favicon  网站图标位置{@favicon}
favicon: /favicon.ico

## Feed ## rss --rss文件位置{@rss}
rss: /atom.xml

## Carousel
carousel:
  img: 
  #'./img/head-img.jpg'
  url: 
  #'javascript:'

# 各个小工具的设置

## widgets 6个左边小工具{@widgets:[notification,category,archive,tagcloud,friends]}
widgets:
  - search
  - notification
  - social
  - category
  - archive
  - tagcloud
  - friends


## 搜索
jsonContent:
  searchLocal: true # 是否启用本地搜索
  searchGoogle: false
  posts:
    title: true
    text: true
    content: true
    categories: true
    tags: true

## 网站公告设置
notification: |-
            <p>
               本站不定期分享开发技术、科学上网教程。
            </p>

## 社交设置{@name:社交工具名字，@icon:社交工具图标，@href:设置工具链接} [参考图标](http://fontawesome.io/icons/)
social:
 - name: Github
   icon: git
   href: //github.com/jiswordsman
 - name: 邮箱
   icon: envelope-o
   href: mailto:jiswordsman@163.com
 - name: 联系QQ
   icon: qq
   href: /85893905
 - name: 微信
   icon: weixin
   href: /
 # - name: QQ群
 #  icon: users
 #  href: /
 - name: RSS
   icon: feed
   href: /atom.xml

## 文章归档设置{@arch_config:/*参数参考：https://hexo.io/zh-cn/docs/helpers.html#list-archives*/}
## 推荐组合方式：[{type: 'monthly',format: 'YYYY年MM月'},{type: 'yearly',format: 'YYYY年'}]
arch_config:
   type: 'monthly'
   format: 'YYYY年MM月'
   show_count: true
   order: -1

## 文章分类设置{@cate_config:{@show_count:是否显示数字，@show_current: 是否高亮当前category}}
cate_config:
   show_count: true
   show_current: true


## 标签云设置
tagcloud:
  tag3d: true
  textColour: '#444'
  outlineMethod: 'block'
  outlineColour: '#FFDAB9'
  interval: 30
  freezeActive: true
  frontSelect: true
  reverse: true
  wheelZoom: true

## 友链设置{@链接名称：链接地址{@links:[,,,]}}
links:
  - 便宜好货: https://m.yunjiglobal.com/yunjibuyer/static/vue-buyer/idc/index.html#/home?shopId=3710029&discoverId=0&appCont=0
  - 我的博客: https://jiyongjun.tk

# 主题自定义个性化配置

## 网站宣传语
branding: To be a better man !

## 设置banner背景图片{@img:imgUrl自定义图片地址,主题默认{"静态背景":"banner.jpg"},{"动态背景":"banner2.jpg"}}
banner:
    img: http://piwgc559z.bkt.clouddn.com/18-12-2/43670187.jpg

  
## 首页列表底部面板
homePanel: true

## 首页文章列表缩略图
### 加载规则: 自定义文章缩略图(在Front-matter中添加的'img'字段) > 文章内的图片 > defaultImgs(随机获取) > 无图模式列表

## 是否显示缩略图
showImgs: false
## 缩略图自定义随机图片
defaultImgs:
  - 

### 文章摘要{@摘要显示优先级：自定义摘要 > 自动截取摘要 }
### 自定义摘要范围{@<!--more-->:截取more之前的内容为摘要}
### 自动截取摘要{@excerptLength:自动截取文章前多少个字为摘要，不配置默认：120字}
## 截取文章首页描述字数
excerptLength: 120

## 是否开启文章目录
toc: true

## 代码高亮配置{@highlightTheme: 主题名称,(配置暂时不可用，后续开发中…)}
highlightTheme:

## bootstrap配置
bootstrap:

## ICON配置 (不配则启用本地Font Icon)
fontAwesome: //cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css

## 文章过期提醒功能
warning:
  days: 300
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 文章内声明{@declaration: {enable:是否开启,title:声明标题,tip:提示内容}}
declaration:
  enable: true
  title: '转载声明'
  tip: |-
      商业转载请联系作者获得授权,非商业转载请注明出处 © <a href="https://cgfw.tk" target="_blank">cgfw.tk</a>

## 文章打赏{@reward: {alipay:支付宝打赏,wepay:微信打赏,tip:打赏提示语; 链接都为空,关闭打赏功能}}
reward:
  alipay: ''
  wepay: '../img/reward-wepay.png'
  tip: 赞赏是不耍流氓的鼓励

## 主题评论

### gitment
gitment:
  enable: false
  owner:
  repo:
  client_id:
  client_secret:
  perPage: 10

### 来必力
livere:
  enable: false
  livere_uid: MTAyMC80MTI1My8xNzgwMQ

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id: 1966422

### Disqus评论
disqus:
  enable: false
  shortname: snippet
  count: false

### 畅言评论(需要ICP备案)
changyan:
  enable: false
  appid:
  conf:

## Valine评论
valine:
   enable: true
   appId: cTOl02NUymv4WNJkBpWObY4R-gzGzoHsz
   appKey: tgImVWH5m4ofgqwHGpAu9X8C
   placeholder: 说点什么吧
   notify: false
   verify: false
   avatar: mm
   meta: nick,mail
   pageSize: 10

## 网站访客统计[不蒜子统计](http://busuanzi.ibruce.info/)
visit_counter:
   site: true
   page: true

## 网站访问统计分析

### 网盟CNZZ统计
cnzz_analytics: 1263868967

### 百度统计  [百度统计](https://tongji.baidu.com/)
baidu_analytics: 23fd0abd0e8fe7f359c97606e9e06cd4

### 谷歌统计
google_analytics: 23fd0abd0e8fe7f359c97606e9e06cd4

### 腾讯分析
tencent_analytics:

### 百度站点认证
baidu_site_verification: UQWgMENrW1
### 百度ssp认证
baidu_ssp_verify: eb1e6f1398f76db6d969b0cfd3bfed53

### 百度自动推送(@baidu_push: 是否启用百度自动推送)  参考网站: [百度站长资源](https://ziyuan.baidu.com/college/courseinfo?id=267&page=2#h2_article_title18)
baidu_push: true

#网站主题配置
since: 2018
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.0.0
